### ISSUE TITLE
Segmentation fault..

### ISSUE THREAD

**Issue by riemers** [steynovich/docker-spotweb#1]
```Attaching to spotweb
spotweb       | Check if db is online ...
spotweb       | Retrying ...
spotweb       | Segmentation fault (core dumped)
spotweb       | Retrying ...
spotweb       | Segmentation fault (core dumped)
spotweb       | Retrying ...
spotweb       | Segmentation fault (core dumped)
```
I don't think it should be doing this ;) i was more eager to use your version since it just depends on a normal mariadb service, while others make their own "sausage" db for spotweb. I use my db for more, hence why i wanted this version to work. Could you check/update to latest version?

**Comment by steynovich** [comment]
No that's not exactly expected behaviour. Can you provide me some info? Which version of Docker and which container tag are you using?

And can you try the latest tag (steynovich/spotweb:20170813 ) and try to start the mysql binary in the spotweb container?

```
$ docker run --rm -ti steynovich/spotweb:20170813 mysql -V
mysql  Ver 15.1 Distrib 10.1.22-MariaDB, for Linux (x86_64) using readline 5.1
```

**Comment by riemers** [comment]
latest tag doesn't exist btw on docker hub. But i used the latest one, that didn't solve anything. Looking further into the container i was able to see that since i "added" this to my docker compose the -links option doesn't propagate the ENV's from the database server incorrectly (as in, they are empty) so i added these to my docker-compose spotweb section:
```
            - MYSQL_PORT_3306_TCP_ADDR=database
            - MYSQL_ENV_MYSQL_DATABASE=spotweb
            - MYSQL_ENV_MYSQL_USER=spotweb
            - MYSQL_ENV_MYSQL_PASSWORD=${MYSQL_ENV_MYSQL_PASSWORD}
```
And added the password to a .env file so it loads on compose.

After that it started to work, since it does load the profile.sh correctly. Had some issues with some spots since i moved my old database into this one (so might have some different tables?)

Lastly, i noticed some errors in the nginx logs:
2017/08/25 21:19:41 [crit] 22#0: *202 connect() to [::1]:9000 failed (99: Address not available) while connecting to upstream, client: , could this be that its doing some ipv6 which is not on?

p.s. that means, i don't use volumes for the db and cache folder, i just use a folder on the host system.

**Comment by steynovich** [comment]
This is my running config `docker-compose.yml`, mysql env is propagated in the spotweb container with the `links` setting:

```yaml
version: '2'
services:
  database:
    image: mariadb:10.2.8
    environment:
      MYSQL_DATABASE: OBFUSCATED
      MYSQL_PASSWORD: spotweb
      MYSQL_ROOT_PASSWORD: OBFUSCATED
      MYSQL_USER: spotweb
    volumes:
    - /mnt/vol/spotweb_db:/var/lib/mysql
  web:
    image: steynovich/spotweb:20170826
    volumes:
    - /mnt/vol/spotweb_cache:/var/www/html/spotweb/cache
    links:
    - database:mysql
```


With regards to the database issue, try to run upgrade-db.php. Maybe altering the database scheme failed because of the missing env vars.
```
$ php /var/www/html/spotweb/bin/upgrade-db.php
```

Just pushed a new container tag (`20170826`) to fix the issue with nginx and IPv6

**Comment by riemers** [comment]
Tried the upgrade too, but could be because i was not having the latest tag yet. I took one before that was older to check if all was ok, might have been that. (running manual retrieve, results in no errors) but i do see spots now that are not verified, will wait till tomorrow and check again. Should have run enough then.

Could you also add the "latest" tag? on docker hub? Is easier 👍 

Thanks for the nginx fix.

This is my config now:
```
    spotweb:
        image: steynovich/spotweb:20170826
        container_name: spotweb
        links:
            - database:mysql
        ports:
            - 80:80/tcp
        environment:
            - MYSQL_PORT_3306_TCP_ADDR=database
            - MYSQL_ENV_MYSQL_DATABASE=spotweb
            - MYSQL_ENV_MYSQL_USER=spotweb
            - MYSQL_ENV_MYSQL_PASSWORD=${MYSQL_ENV_MYSQL_PASSWORD}
        volumes:
            - ${CONFIG}/spotweb/cache:/var/www/html/spotweb/cache
            - ${DATA}/Downloads/nzb:/nzb

    database:
        image: mariadb:latest
        container_name: database
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
        volumes:
            - ${CONFIG}/database:/var/lib/mysql
```

Have to add those environment entry's to the spotweb one, otherwise it does not work. (compose version 2 file)

**Comment by steynovich** [comment]
Although I think the latest tag is bad concept I'm now pushing the tag `steynovich/spotweb:latest` again

**Comment by riemers** [comment]
Could you say why? Perhaps you have the right reasons, but i normally find
it handy. If I want to stay on a particular versio I would choose that one
instead. Just curious..

Op 26 augustus 2017 om 14:10:51, Steyn Huizinga (notifications@github.com)
schreef:

**Comment by riemers** [comment]
p.s. post updates seems to be running ok, so it is only a "drawback" that i have to add the ENV entry's in my docker compose. Besides that, all seems to be working.

**Comment by steynovich** [comment]
Strange... with this config:

```yml
services:
    spotweb:
        image: steynovich/spotweb:20170826
        container_name: spotweb
        links:
            - database:mysql
        ports:
            - 80:80/tcp
        environment:
            - MYSQL_PORT_3306_TCP_ADDR=database
            - MYSQL_ENV_MYSQL_DATABASE=spotweb
            - MYSQL_ENV_MYSQL_USER=spotweb
            - MYSQL_ENV_MYSQL_PASSWORD=spotweb
    database:
        image: mariadb:latest
        container_name: database
        environment:
            - MYSQL_ROOT_PASSWORD=spotweb
            - MYSQL_USER=spotweb
            - MYSQL_PASSWORD=spotweb
            - MYSQL_DATABASE=spotweb
```

The env vars in the spotweb container are
```bash
$ docker exec spotweb env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=f9ff393e44dd
MYSQL_ENV_MYSQL_USER=spotweb
MYSQL_ENV_MYSQL_DATABASE=spotweb
MYSQL_PORT_3306_TCP_ADDR=database
MYSQL_ENV_MYSQL_PASSWORD=spotweb
...
```

Docker 17.07.0-ce-rc2
